version: '3.7'

services:
  orderbook:
    container_name: orderbook
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
